Stat/Debuff/Mobility/Family Headers
BenLanglois/Hackmon pull request #2
Opened 2019-07-12 20:06 UTC by ariellam

2019-07-13 20:44 UTC, alexgirard approved these changes
Overall looks good :)

2019-07-13 20:44 UTC, alexgirard commented on .vscode/settings.json
> +{
pretty sure this shouldn't be here lol

2019-07-13 20:44 UTC, alexgirard commented on game/Makefile
> +OBJECTS = action.o hackmon.o
maybe remove the changes to the file so that they don't conflict? since they're not really necessary

2019-07-13 20:44 UTC, alexgirard commented on game/debuffInfo.h
> +#include "statInfo.h"
I don't think `statInfo.h` needs to be included here

2019-07-13 20:44 UTC, alexgirard commented on game/debuffInfo.h
> +#include "statInfo.h"
or `map`

2019-07-13 22:14 UTC, BenLanglois requested changes

2019-07-13 22:14 UTC, BenLanglois commented on .vscode/settings.json
> +{
You should add it to the .gitignore

2019-07-13 22:14 UTC, BenLanglois commented on game/Makefile
> +OBJECTS = action.o hackmon.o
I've changed the Makefile a bit on my branch (action-header / action-implementation) so don't worry about it too much

2019-07-13 22:14 UTC, BenLanglois commented on game/family.h
> +    std::size_t effectiveness(Family otherFamily);
Don't need `std::` for `size_t`

2019-07-13 22:14 UTC, BenLanglois commented on game/family.h
> +#include <string>
Don't need the `<string>` library

2019-07-13 22:14 UTC, BenLanglois commented on game/mobility.h
> +class Mobility {
As discussed, `Mobility` will need a reference to the Hackmon

2019-07-13 22:14 UTC, BenLanglois commented on game/stats.cc
> +      hp = newValue;
HP should check to make sure it's not negative or higher than max

2019-07-13 22:14 UTC, BenLanglois commented on game/stats.cc
> +      attack = newValue;
ATTACK, DEFENSE, and SPEED should check to make sure they are within their bounds. I think we agreed on +/- 5? Maybe you could make this a static variable in the `Stats` class

2019-07-13 22:14 UTC, BenLanglois commented on game/type.h
> +  normal,
I believe we agreed upon UPPER_CASE convention for enum values

2019-07-14 00:30 UTC, BenLanglois reviewed
A few minor changes

2019-07-14 00:30 UTC, BenLanglois commented on game/confusion.h
> +    Confusion();
Do you need a Hackmon as a parameter?

2019-07-14 00:30 UTC, BenLanglois commented on game/mobility.h
> +#include "hackmon.h"
I think a forward-declare is enough, you shouldn't need to include hackmon.h

2019-07-14 00:30 UTC, BenLanglois commented on game/stats.cc
> +Stats::Stats(const int mapHp, const int baseAttack, const int baseDefense, const int baseSpeed) :
These shouldn't be const

2019-07-14 00:30 UTC, BenLanglois commented on game/stats.h
> +    Stats(const int, const int, const int, const int);
Don't forget to update the header as well

2019-07-14 00:42 UTC, BenLanglois approved these changes

2019-07-14 00:42 UTC, merged