Action header
BenLanglois/Hackmon pull request #3
Opened 2019-07-13 22:18 UTC by BenLanglois

Header files for Actions, which include Moves and Items. Still working on the implementation files on the action-implementation branch.

2019-07-13 22:32 UTC, alexgirard requested changes
Looks good! Small naming change

2019-07-13 22:32 UTC, alexgirard commented on game/debuffHeal.h
> +class Potion: public Item {
how come this class is named `Potion` when the file name is `debuffHeal`? Our UML shows both classes

2019-07-13 22:32 UTC, alexgirard commented on game/potion.h
> +class Potion: public Item {
Ya I think it was a copypasta error above

2019-07-13 22:48 UTC, ariellam commented on game/action.h
> +  virtual void doActionOverride(Player &player, const std::vector<size_t> &targets) const = 0;
Remove param names from method files

2019-07-14 00:23 UTC, ariellam approved these changes
lgtm 👍

2019-07-14 00:23 UTC, ariellam commented on game/debuffHeal.h
> +  DebuffName debuff;
can we make this const?

2019-07-14 00:38 UTC, alexgirard approved these changes
Looks good!

2019-07-14 00:39 UTC, merged